version: '3.8'

services:
  moodle:
    image: bitnami/moodle:latest
    ports:
      - "80:8080"
      - "443:8443"
    volumes:
      - moodle_data:/bitnami
    environment:
      - MOODLE_DATABASE_HOST=mariadb
      - MOODLE_DATABASE_PORT_NUMBER=3306
      - MOODLE_DATABASE_USER=moodle
      - MOODLE_DATABASE_PASSWORD=moodle_password
      - MOODLE_DATABASE_NAME=moodle
      - MOODLE_USERNAME=admin
      - MOODLE_PASSWORD=admin_password
      - MOODLE_EMAIL=admin@example.com
    depends_on:
      - mariadb

  mariadb:
    image: bitnami/mariadb:latest
    volumes:
      - mariadb_data:/bitnami/mariadb
    environment:
      - MARIADB_ROOT_PASSWORD=root_password
      - MARIADB_USER=moodle
      - MARIADB_PASSWORD=moodle_password
      - MARIADB_DATABASE=moodle
      - MOODLE_LANGUAGE=es

volumes:
  moodle_data:
    driver: local
  mariadb_data:
    driver: local
